const assert = require('node:assert/strict');
require('../badge-design.js');
const D = globalThis.BadgeDesign;
const rows = D.normalize([{id:'a',name:'預設',content:'QR-A',isDefault:true},{id:'b',name:'班員',content:'QR-B'}]);
rows[0].fields[0].value='王小明';
assert.equal(D.resolve(rows,rows[1],'name').value,'王小明');
rows[0].fields[0].value='林小華';
assert.equal(D.resolve(rows,rows[1],'name').value,'林小華');
rows[1].fields[0].mode='own';rows[1].fields[0].value='陳大同';
assert.equal(D.resolve(rows,rows[1],'name').value,'陳大同');
rows[0].fields[0].mode='reference';rows[0].fields[0].sourceId='b';
assert.equal(D.resolve(rows,rows[0],'name').value,'陳大同');
rows[1].fields[0].mode='default';
assert.match(D.resolve(rows,rows[0],'name').error,/循環/);
rows[0].fields[0].mode='own';
D.detachReferences(rows,'a');
assert.equal(rows[1].fields[0].mode,'own');
assert.equal(rows[1].fields[0].value,'林小華');
assert.equal(rows[1].content,'QR-B');
assert.deepEqual(D.normalize(JSON.parse(JSON.stringify(rows))),rows);
assert.deepEqual(D.normalize({}),[]);
assert.equal(D.normalize([{id:"x');evil()",name:'x',content:'x'}]).length,0);
assert.equal(D.normalize([...rows,...rows]).length,2);
console.log('PASS: legacy migration, inheritance, live references, overrides, cycles, deletion, QR isolation, backup roundtrip, validation');
